// app/layout.jsx

import "./globals.css";
import type { Metadata } from 'next'
import Navbar from "./component/navbar";
import Footer from "./component/footer";
import { Providers } from "./provider";

export const metadata: Metadata = {
    title: 'Alpha',
    description: 'Social app Generated by create next app',
  }
  

export default function RootLayout({ children }:any) {
  return (
    <html suppressHydrationWarning>
      <head />
      <body>
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
